### ISSUE TITLE
Error sensu-handler.rb

### ISSUE THREAD

**Issue by vvm7ua** [sensu-plugins/sensu-plugins-mailer#11]
Get the next error:
# cat /etc/sensu/conf.d/mailer.json | /opt/sensu/embedded/bin/ruby /etc/sensu/handlers/handler-mailer.rb 
/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:128:in `+': no implicit conversion of nil into String (TypeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:128:in `filter_silenced'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:31:in `filter'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'

Can you help?

Thanks!

**Comment by vvm7ua** [comment]
Just configuration issue.

**Comment by zoell** [comment]
What was the configuration issue? I have the same problem.

**Comment by thebenwaters** [comment]
same
