### ISSUE TITLE
-j, --json_config help text and documentation are misleading

### ISSUE THREAD

**Issue by Hydrochoerus** [sensu-plugins/sensu-plugins-mailer#42]
The help text for -j, --json_config is misleading. The text is not completely clear that it means a global sensu configuration json key which stores the configuration. I initially thought that the param points to a file containing the config. The comments in the handler do not help either:

```
# Note: The default mailer config is fetched from the predefined json config file which is "mailer.json" or any other
#       file defiend using the "json_config" command line option.
```

Changing

```
-j, --json_config JsonConfig     Config Name
```

to

```
-j, --json_config JsonKey     Sensu config key containing mailer settings
```

or something similar might help a bit. 

Alternatively changing the logic to match the documentation would be acceptable.

**Comment by majormoses** [comment]
closed via #51
