### ISSUE TITLE
Is is possible to have a customizable subject?

### ISSUE THREAD

**Issue by beastea** [sensu-plugins/sensu-plugins-mailer#6]
I would like you to add an option to make a subject customizable.
Thanks in advance.

**Comment by eheydrick** [comment]
You can use the `notification` setting of the check to customize the message that's included in the subject. PRs welcome for any further customization.

**Comment by eheydrick** [comment]
@beastea Will that meet your needs or did you have something else in mind?

**Comment by nathanhruby** [comment]
So I ran into this today.  Specifically for my use case, it'd be nice to have a subject prefix as a config option (something like "[sensu]") to make for easy filtering by eye and via a mail filter.  

Adding this on every check config seems redundant and the right place seems like at the handler.
