### ISSUE TITLE
Please tag and release 90c249f42b1f7eced03e562c44ebe457e43915db

### ISSUE THREAD

**Issue by ryanneufeld** [sensu-plugins/sensu-plugins-mailer#8]
https://github.com/sensu-plugins/sensu-plugins-mailer/commit/90c249f42b1f7eced03e562c44ebe457e43915db This commit fixes a problem with the mailgun script that I am experiencing at the moment.

The only other option I have to fix it, is to hack the files after they've been installed.

**Comment by eheydrick** [comment]
[0.1.0](https://rubygems.org/gems/sensu-plugins-mailer/versions/0.1.0) has been released.
